/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.2
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <Pin_PWM_Blue_3_aliases.h>
#include <Pin_PWM_Blue_3.h>
#include <PrISM_3.h>
#include <PrISM_6.h>
#include <Pin_PWM_Warm_3_aliases.h>
#include <Pin_PWM_Warm_3.h>
#include <Pin_PWM_Blue_2_aliases.h>
#include <Pin_PWM_Blue_2.h>
#include <PrISM_5.h>
#include <Pin_PWM_Cool_2_aliases.h>
#include <Pin_PWM_Cool_2.h>
#include <Pin_PWM_Warm_2_aliases.h>
#include <Pin_PWM_Warm_2.h>
#include <PrISM_4.h>
#include <Pin_PWM_Blue_1_aliases.h>
#include <Pin_PWM_Blue_1.h>
#include <Pin_PWM_Cool_1_aliases.h>
#include <Pin_PWM_Cool_1.h>
#include <Pin_PWM_Cool_3_aliases.h>
#include <Pin_PWM_Cool_3.h>
#include <Pin_PWM_Warm_1_aliases.h>
#include <Pin_PWM_Warm_1.h>
#include <Pin_PWM_Blue_0_aliases.h>
#include <Pin_PWM_Blue_0.h>
#include <Clock_1.h>
#include <PrISM_2.h>
#include <USBUART_Central.h>
#include <USBUART_Central_audio.h>
#include <USBUART_Central_cdc.h>
#include <USBUART_Central_hid.h>
#include <USBUART_Central_midi.h>
#include <PrISM_1.h>
#include <Pin_PWM_Cool_0_aliases.h>
#include <Pin_PWM_Cool_0.h>
#include <Pin_PWM_Warm_0_aliases.h>
#include <Pin_PWM_Warm_0.h>
#include <Pin_PWM_Warm_4_aliases.h>
#include <Pin_PWM_Warm_4.h>
#include <PrISM_7.h>
#include <Pin_PWM_Cool_4_aliases.h>
#include <Pin_PWM_Cool_4.h>
#include <PrISM_8.h>
#include <Pin_PWM_Blue_4_aliases.h>
#include <Pin_PWM_Blue_4.h>
#include <Pin_PWM_Warm_5_aliases.h>
#include <Pin_PWM_Warm_5.h>
#include <PrISM_9.h>
#include <Pin_PWM_Cool_5_aliases.h>
#include <Pin_PWM_Cool_5.h>
#include <Pin_PWM_Blue_5_aliases.h>
#include <Pin_PWM_Blue_5.h>
#include <PrISM_10.h>
#include <Pin_PWM_Warm_6_aliases.h>
#include <Pin_PWM_Warm_6.h>
#include <Pin_PWM_Cool_6_aliases.h>
#include <Pin_PWM_Cool_6.h>
#include <PrISM_11.h>
#include <Pin_PWM_Blue_6_aliases.h>
#include <Pin_PWM_Blue_6.h>
#include <Pin_PWM_Warm_7_aliases.h>
#include <Pin_PWM_Warm_7.h>
#include <PrISM_12.h>
#include <Pin_PWM_Cool_7_aliases.h>
#include <Pin_PWM_Cool_7.h>
#include <Pin_PWM_Blue_7_aliases.h>
#include <Pin_PWM_Blue_7.h>
#include <PrISM_13.h>
#include <Pin_PWM_Warm_8_aliases.h>
#include <Pin_PWM_Warm_8.h>
#include <Pin_PWM_Cool_8_aliases.h>
#include <Pin_PWM_Cool_8.h>
#include <PrISM_14.h>
#include <Pin_PWM_Blue_8_aliases.h>
#include <Pin_PWM_Blue_8.h>
#include <UART_Debug.h>
#include <UART_Sensor.h>
#include <Pin_Panel_LED_0_aliases.h>
#include <Pin_Panel_LED_0.h>
#include <Pin_Panel_LED_1_aliases.h>
#include <Pin_Panel_LED_1.h>
#include <Pin_Panel_LED_2_aliases.h>
#include <Pin_Panel_LED_2.h>
#include <Pin_Debug_LED_aliases.h>
#include <Pin_Debug_LED.h>
#include <Pin_Debug_Button_aliases.h>
#include <Pin_Debug_Button.h>
#include <USBUART_Central_Dm_aliases.h>
#include <USBUART_Central_Dm.h>
#include <USBUART_Central_Dp_1_aliases.h>
#include <USBUART_Central_Dp_1.h>
#include <UART_Debug_IntClock.h>
#include <UART_Sensor_IntClock.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/
