/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <Pin_12_aliases.h>
#include <Pin_12.h>
#include <PrISM_3.h>
#include <PrISM_6.h>
#include <Pin_10_aliases.h>
#include <Pin_10.h>
#include <Pin_9_aliases.h>
#include <Pin_9.h>
#include <PrISM_5.h>
#include <Pin_8_aliases.h>
#include <Pin_8.h>
#include <Pin_7_aliases.h>
#include <Pin_7.h>
#include <PrISM_4.h>
#include <Pin_6_aliases.h>
#include <Pin_6.h>
#include <Pin_5_aliases.h>
#include <Pin_5.h>
#include <Pin_11_aliases.h>
#include <Pin_11.h>
#include <Pin_4_aliases.h>
#include <Pin_4.h>
#include <Pin_3_aliases.h>
#include <Pin_3.h>
#include <Clock_1.h>
#include <PrISM_2.h>
#include <USBUART_1.h>
#include <USBUART_1_audio.h>
#include <USBUART_1_cdc.h>
#include <USBUART_1_hid.h>
#include <USBUART_1_midi.h>
#include <PrISM_1.h>
#include <Pin_2_aliases.h>
#include <Pin_2.h>
#include <Pin_1_aliases.h>
#include <Pin_1.h>
#include <Pin_13_aliases.h>
#include <PrISM_7.h>
#include <Pin_14_aliases.h>
#include <PrISM_8.h>
#include <Pin_15_aliases.h>
#include <Pin_15.h>
#include <Pin_16_aliases.h>
#include <Pin_16.h>
#include <PrISM_9.h>
#include <Pin_17_aliases.h>
#include <Pin_17.h>
#include <Pin_18_aliases.h>
#include <Pin_18.h>
#include <PrISM_10.h>
#include <Pin_19_aliases.h>
#include <Pin_19.h>
#include <Pin_20_aliases.h>
#include <Pin_20.h>
#include <PrISM_11.h>
#include <Pin_21_aliases.h>
#include <Pin_21.h>
#include <Pin_22_aliases.h>
#include <Pin_22.h>
#include <PrISM_12.h>
#include <Pin_23_aliases.h>
#include <Pin_23.h>
#include <Pin_24_aliases.h>
#include <Pin_24.h>
#include <PrISM_13.h>
#include <Pin_25_aliases.h>
#include <Pin_25.h>
#include <Pin_26_aliases.h>
#include <Pin_26.h>
#include <PrISM_14.h>
#include <Pin_27_aliases.h>
#include <Pin_27.h>
#include <Pin_28_aliases.h>
#include <Pin_28.h>
#include <UART_1.h>
#include <USBUART_1_Dm_aliases.h>
#include <USBUART_1_Dp_1_aliases.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/
