/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.0 Component Pack 3
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <VDAC_PulseRef.h>
#include <ADC_PulseIn.h>
#include <LCD.h>
#include <IDAC8_PulseIR.h>
#include <Led_aliases.h>
#include <DMA_dma.h>
#include <Clock.h>
#include <CapSense_1.h>
#include <CapSense_1_CSHL.h>
#include <CapSense_1_Pins.h>
#include <CapSense_1_TunerHelper.h>
#include <UART_LED.h>
#include <UART_Net.h>
#include <Pin_ProxIR_1_aliases.h>
#include <Pin_ProxIR_2_aliases.h>
#include <Pin_ProxIR_3_aliases.h>
#include <AMux_ProxIR.h>
#include <ADC_SAR_ProxIR.h>
#include <TIA_PulseIn.h>
#include <Pin_PulseIn_minus_aliases.h>
#include <Pin_PulseRef_aliases.h>
#include <IDAC8_PulseRed.h>
#include <Pin_DevId0_aliases.h>
#include <Pin_DevId0.h>
#include <Pin_PulseIR_Intensity_aliases.h>
#include <Pin_PulseRed_Intensity_aliases.h>
#include <Opamp_PulseRef.h>
#include <Pin_PulseIn_plus_aliases.h>
#include <Filter_PulseInBand.h>
#include <Filter_PulseInBand_PVT.h>
#include <Clock_PWM_PulseLEDs.h>
#include <Pin_PulseIR_on_aliases.h>
#include <Pin_PulseIR_on.h>
#include <Pin_PulseRed_on_aliases.h>
#include <Pin_PulseRed_on.h>
#include <PWM_PulseLEDs.h>
#include <isr_PulseReadAmbient.h>
#include <isr_PulseReadIR.h>
#include <PrISM_PulseIndicator.h>
#include <Pin_PulseIndicator_aliases.h>
#include <Pin_PulseIndicator.h>
#include <Clock_1.h>
#include <ADC_PulseIn_Ext_CP_Clk.h>
#include <ADC_PulseIn_theACLK.h>
#include <ADC_PulseIn_AMux.h>
#include <LCD_LCDPort_aliases.h>
#include <LCD_LCDPort.h>
#include <CapSense_1_CompCH0.h>
#include <CapSense_1_AMuxCH0.h>
#include <CapSense_1_IntClock.h>
#include <ADC_SAR_ProxIR_theACLK.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/
