/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <VDAC_PulseRef.h>
#include <ADC_PulseIn.h>
#include <Pin_DebugButton_aliases.h>
#include <Pin_DebugButton.h>
#include <IDAC8_PulseIR.h>
#include <Pin_DebugLED_aliases.h>
#include <Pin_PylonType1_aliases.h>
#include <Pin_PylonType1.h>
#include <Pin_PylonType0_aliases.h>
#include <Pin_PylonType0.h>
#include <CapSense_1.h>
#include <CapSense_1_CSHL.h>
#include <CapSense_1_Pins.h>
#include <CapSense_1_TunerHelper.h>
#include <UART_Debug.h>
#include <UART_Net.h>
#include <Pin_ProxIR_1_aliases.h>
#include <ADC_SAR_ProxIR.h>
#include <TIA_PulseIn.h>
#include <Pin_PulseIn_minus_IRD_C_aliases.h>
#include <Pin_PulseRef_IRD_A_aliases.h>
#include <IDAC8_PulseRed.h>
#include <Pin_PulseIR_Intensity_aliases.h>
#include <Pin_PulseRed_Intensity_aliases.h>
#include <Opamp_PulseRef.h>
#include <Pin_PulseIn_plus_IRD_A_aliases.h>
#include <Filter_PulseInBand.h>
#include <Filter_PulseInBand_PVT.h>
#include <Clock_PWM_PulseLEDs.h>
#include <Pin_PulseIR_on_aliases.h>
#include <Pin_PulseIR_on.h>
#include <Pin_PulseRed_on_aliases.h>
#include <Pin_PulseRed_on.h>
#include <PWM_PulseLEDs.h>
#include <isr_PulseReadAmbient.h>
#include <isr_PulseReadIR.h>
#include <Pin_BrightLEDCool_aliases.h>
#include <Pin_BrightLEDCool.h>
#include <PrISM_LEDCool.h>
#include <Prism_LED_Clock.h>
#include <ShiftReg_DelaySenseIR.h>
#include <Pin_BrightLEDWarm_aliases.h>
#include <Pin_BrightLEDWarm.h>
#include <PrISM_LEDWarm.h>
#include <Pin_BrightLEDBlue_aliases.h>
#include <Pin_BrightLEDBlue.h>
#include <USBUART_1.h>
#include <USBUART_1_audio.h>
#include <USBUART_1_cdc.h>
#include <USBUART_1_hid.h>
#include <USBUART_1_midi.h>
#include <PrISM_LEDBlue.h>
#include <Pin_Rx_Net_Enable_aliases.h>
#include <Pin_Rx_Net_Enable.h>
#include <Pin_Tx_Net_Enable_aliases.h>
#include <Pin_Tx_Net_Enable.h>
#include <ADC_PulseIn_theACLK.h>
#include <ADC_PulseIn_Ext_CP_Clk.h>
#include <ADC_PulseIn_AMux.h>
#include <CapSense_1_CompCH0.h>
#include <CapSense_1_IdacCH0.h>
#include <CapSense_1_AMuxCH0.h>
#include <CapSense_1_IntClock.h>
#include <ADC_SAR_ProxIR_theACLK.h>
#include <USBUART_1_Dm_aliases.h>
#include <USBUART_1_Dp_1_aliases.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/
